package com.starbox.engine;

public enum GameEventType {
    PLAYER_SHOT_SINGLE,
    PLAYER_SHOT_SPREAD,
    PLAYER_SHOT_MULTI,
    PLAYER_SHOT_RAPID,
    PLAYER_HIT,
    PLAYER_KILLED,

    ENEMY_SHOT_SINGLE,
    ENEMY_SHOT_AIMED,
    ENEMY_SHOT_SPREAD,
    ENEMY_HIT,
    ENEMY_KILLED,

    BOSS_SHOT_SINGLE,
    BOSS_SHOT_AIMED,
    BOSS_SHOT_SPREAD,
    BOSS_HIT,
    BOSS_KILLED
}
